spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/ticketing_app
    username: root
    password: Amill2017
    driver-class-name: org.mariadb.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587 # or 465
    username: chimbirotawanda@gmail.com
    password: rfsz mmfo pilw gyov
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


motapa:
  api:
    base-url: https://api.motapa.africa/v1
    secret-key: pk_test_DHYQjCldE5EVqib2pHnvLJXhbNC1rBZl

server:
  port: 8099